clear all
close all
clc

Div_Hori_FasterCNN_Yasser_Resnet18_anchors_v5_XXEpo_Train_Test
Div_Hori_FasterCNN_Yasser_Resnet50_anchors_v5_XXEpo_Train_Test
Div_Hori_FasterCNN_Yasser_Squeeze_anchors_v5_XXEpo_Train_Test
Div_Hori_FasterCNN_Yasser_Googlenet_anchors_v5_XXEpo_Train_Test